### ISSUE TITLE
Roboto doesn't support cyrillic

### ISSUE THREAD

**Issue by TrySound** [jonathantneal/google-fonts-complete#1]
I got the same link from google fonts and it's correct.
Works:

``` css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'),
    url(https://fonts.gstatic.com/s/roboto/v15/mErvLBYg_cXG3rLvUsKT_fesZW2xOQ-xsNqO47m55DA.woff2) format('woff2');
}
```

Doesn't:

``` css
@font-face {
  font-family: Roboto;
  font-style: normal;
  font-weight: 400;
  src: url(//fonts.gstatic.com/s/roboto/v15/CWB0XYA8bzo0kSThX0UTuA.woff2) format("woff2"),
    url(//fonts.gstatic.com/s/roboto/v15/2UX7WLTfW3W8TclTUvlFyQ.woff) format("woff"),
    url(//fonts.gstatic.com/s/roboto/v15/zN7GBFwfMP4uA6AR0HCoLQ.ttf) format("truetype");
}
```
